# BoW 기반 텍스트 분석 연습 
- 3/3/26 Tue
1. 적절한 데이터셋을 찾거나 생성하고, 적절한 전처리를 진행한다. [01_preprocessing.ipynb]
2. TF-IDF Vectorizer를 이용하여 벡터화한다.
3. Cosine Similarity를 계산하여 입력된 문자열의 긍/부정을 판단한다.

- files 05-09

- 3/4/26 Wed
1. learned Word Embedding so vectorize with WE


jsonl 형식 
from desktop 


In [ ]:
# # korean font setting
# import platform
# import matplotlib.pyplot as plt 

# if platform.system() == 'Darwin': # macOS
#     plt.rc('font', family='AppleGothic')
# elif platform.system() == 'Windows':
#     plt.rc('font', family='Malgun Gothic')

# plt.rcParams['axes.unicode_minus'] = False

In [8]:
import json

with open('corpus_text.json', 'r', encoding='utf-8') as f:
    corpus_text = json.load(f)

In [9]:
print(type(corpus_text))
print(len(corpus_text))

<class 'list'>
5265


In [10]:
corpus_text

['음악 소리 때문 집중 안되다',
 '콘투락투벡스 콜라겐 생 성 억제 되다 그렇다 프락 셀 시술 받다 콜라겐 생 성 원리 인데 콘투락 투 바르다 안되다',
 '여드름 흉터 색소 침착 돼다 갈색 인데 덥다 스틱 vs 콘투락 투 벡스 걸 추천 하다',
 '얼굴 식초 검버섯 빼다 빨리 제거 안해 서 그렇다 빨갛다 댓 어요 피부 도 만지다 보다 약 굳은살 처럼 느껴지다 알로 젤로 진정 고 연 천 해주다',
 '좋다 영상 감사하다 미취 학 아동 은 걸 바르다 좋다',
 '눈썹 거 상술 하다 일주일 뒤 실밥 뽑다 더마틱스 울트라 겔 바르다 한 달 정도 바르도 살이 울퉁불퉁 하다 요',
 '선생님 2 주전 얼굴 찰 과상 입다 다 아물다 스카 힐 바르다 더 붉다 발라 도 되다',
 '켈 이드 현재 진행중 인데 노스 카나 바르다 안되다',
 '노스 카나 더마틱스 하다 용하다 는 노스 카나 먼저 사용 라고 하다 뭐 맞다 가요',
 '콘트라 투 벡스 랑 더마 틱 스 울트라 순서 는 콘트라 투 벡스 먼저 바르다 안 되다 두 가지 다 바르다 며칠 안 되어다 얼굴 여드름 붉다 흉터 주변 붉다 가려움 안 맞다 건가 요 참고 발라 하나요',
 '노스 카나 랑 더막틱스 울트라 써다 되다',
 '이름 영상 자다 보다 벤트 락스 겔 대한 소견 은 어떻다 신지 여쭈다 보다',
 '사타구니 틀다 살이 음경 수술 부분 써다 되다 흉터 예전 의사 은 이렇게 대충 꼬매 놓다 모르다 새롭다 부분 절제 하고 시술 받다 아니다 약 이나 시술 받다 싶다 약 써다 보고 싶다',
 '스킨 오일 크림 노스 카나 울트라 이렇게 총 5 개 바르다 괜찮다 너무 많이 바르다 가요',
 '이름 안녕하다 뺨 울퉁불퉁하다 않다 빨갛다 흔적 자국 여러 개 여드름 날 처럼 하다 안 곪 고 그대로 흉터 남다 피부 가보다 그냥 해결 해주다 지금 고민 중 인 약 노스 카나 겔 콘트락 투 벡스 벤트 락스 겔 스카 힐 더마틱스 울트라 겔 5 개 중 사용 하다 하다 요 추출 물 연고 먼저 바르다 더마틱스 울트라 겔 덧 바르다 제일 좋다 건

### word frequency

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

count_vectorizer = CountVectorizer(
    ngram_range=(1, 2),   
    max_features=50     
)
corpus_vecs = count_vectorizer.fit_transform(corpus_text)  
print(f"vector size {corpus_vecs.toarray().shape}")     # (sentence, word) 

# vocabulary & frequency

word_counts = corpus_vecs.toarray().sum(axis=0)    # frequency calculation     
vocab = sorted(count_vectorizer.vocabulary_.items(), key=lambda x: x[1])

vocab_df = pd.DataFrame(vocab, columns=['word', 'idx'])
vocab_df['count'] = vocab_df['idx'].apply(lambda i: word_counts[i]) 
vocab_df = vocab_df.drop(columns=['idx']) #drop (unnecessary)
vocab_df = vocab_df.sort_values('count', ascending=False).reset_index(drop=True)

print(vocab_df)

vector size (5265, 50)
       word  count
0        하다   2467
1        먹다   2260
2        되다   1143
3        좋다    844
4        없다    599
5        들다    566
6        보다    548
7        영상    512
8        과일    484
9        이다    482
10       과당    473
11       끊다    473
12       많이    465
13       그냥    451
14       제로    437
15       콜라    436
16      괜찮다    436
17       가다    423
18     감사하다    413
19      비타민    393
20      줄이다    382
21      안좋다    378
22       이름    377
23      아니다    360
24      드리다    355
25       않다    355
26      겁니다    348
27       하고    343
28      그렇다    337
29       알콜    320
30       말다    318
31       섭취    310
32    제로 콜라    296
33       설탕    284
34       처럼    283
35      되어다    282
36       보시    281
37    먹다 되다    279
38       때문    279
39       에는    265
40      조금씩    264
41   줄이다 방향    260
42       방향    260
43      마시다    260
44   가다 겁니다    258
45    방향 가다    256
46    끊다 그냥    254
47    그냥 보시    252
48     액상과당    252
49  조금씩 줄이다    251


### TF-IDF Vectorization

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
text_vecs = tfidf_vectorizer.fit_transform(corpus_text)

print(text_vecs.toarray())
print(tfidf_vectorizer.get_feature_names_out())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['00' '000' '0000' ... '힘들다' '힘없다' '힝헝할']


### cosine similarity

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

corpus_vecs_arr = text_vecs.toarray()
first_similarities = cosine_similarity(corpus_vecs_arr[0:1], corpus_vecs_arr) #first against all
print(first_similarities)

# similarity between all of them
all_similarities = cosine_similarity(corpus_vecs_arr, corpus_vecs_arr) #compare all between all
print(all_similarities)


# most similar to first one
sorted_sentences = first_similarities.argsort()[0][::-1]

# top 10 most similar 
for sen in sorted_sentences[1:11]:  # 0 (self) ommitted
    print(f"similarity 유사도: {first_similarities[0][sen]:.4f}")
    print(f"sentence: {corpus_text[sen]}")

[[1.         0.05941023 0.         ... 0.         0.         0.        ]]
[[1.         0.05941023 0.         ... 0.         0.         0.        ]
 [0.05941023 1.         0.14432449 ... 0.         0.         0.        ]
 [0.         0.14432449 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
similarity 유사도: 0.3272
sentence: 음악 대법원 장 오예
similarity 유사도: 0.3263
sentence: 꿀 도 안되다
similarity 유사도: 0.2791
sentence: 많이 들다 영상 보고 본인 도 조심하다 그런 소리 면 안되다
similarity 유사도: 0.2396
sentence: 과일 도 먹다 안되다
similarity 유사도: 0.2251
sentence: 소리 하다 도통 모르다
similarity 유사도: 0.2245
sentence: 그냥 되다 먹다 거 안되다 거 안되다 옛날 계속 뱅뱅 돌다 돌다 내용 이다 이전 엔 김치 나트륨 비속어 서 먹다 안되다 소리 듣다 밍친
similarity 유사도: 0.2201
sentence: 제로 콜라 는 안되다
similarity 유사도: 0.2201
sentence: 제로 콜라 도 안되다
similarity 유사도: 0.1922
sentence: 세상 도대체

### sentiment analysis method 1 
- (negative, positive word  keyword counting method)

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 긍/부정 standard
positive_ref = '괜찮다 좋다 좋아 감사 효과 도움 추천 개선 긍정 최고'
negative_ref = '안되다 안좋다 부작용 싫어 싫다 악화 심하다 나쁨'

def predict_sentiment(input_text):
    texts = [positive_ref, negative_ref, input_text]
    vecs = tfidf_vectorizer.transform(input_text)
    
    # input vs positive cosine similarity 
    pos_score = cosine_similarity(vecs[2], vecs[0])[0][0] #[2] input, [0] positive
    
    # input vs negative cosine similarity 
    neg_score = cosine_similarity(vecs[2], vecs[1])[0][0] #[1] negative
    
    sentiment = 'positive' if pos_score > neg_score else 'negative'
    
    return {
        'text': input_text,
        'positive_score': round(pos_score, 4),
        'negative_score': round(neg_score, 4),
        'sentiment': sentiment
    }

result = predict_sentiment(corpus_text)
result


{'text': ['음악 소리 때문 집중 안되다',
  '콘투락투벡스 콜라겐 생 성 억제 되다 그렇다 프락 셀 시술 받다 콜라겐 생 성 원리 인데 콘투락 투 바르다 안되다',
  '여드름 흉터 색소 침착 돼다 갈색 인데 덥다 스틱 vs 콘투락 투 벡스 걸 추천 하다',
  '얼굴 식초 검버섯 빼다 빨리 제거 안해 서 그렇다 빨갛다 댓 어요 피부 도 만지다 보다 약 굳은살 처럼 느껴지다 알로 젤로 진정 고 연 천 해주다',
  '좋다 영상 감사하다 미취 학 아동 은 걸 바르다 좋다',
  '눈썹 거 상술 하다 일주일 뒤 실밥 뽑다 더마틱스 울트라 겔 바르다 한 달 정도 바르도 살이 울퉁불퉁 하다 요',
  '선생님 2 주전 얼굴 찰 과상 입다 다 아물다 스카 힐 바르다 더 붉다 발라 도 되다',
  '켈 이드 현재 진행중 인데 노스 카나 바르다 안되다',
  '노스 카나 더마틱스 하다 용하다 는 노스 카나 먼저 사용 라고 하다 뭐 맞다 가요',
  '콘트라 투 벡스 랑 더마 틱 스 울트라 순서 는 콘트라 투 벡스 먼저 바르다 안 되다 두 가지 다 바르다 며칠 안 되어다 얼굴 여드름 붉다 흉터 주변 붉다 가려움 안 맞다 건가 요 참고 발라 하나요',
  '노스 카나 랑 더막틱스 울트라 써다 되다',
  '이름 영상 자다 보다 벤트 락스 겔 대한 소견 은 어떻다 신지 여쭈다 보다',
  '사타구니 틀다 살이 음경 수술 부분 써다 되다 흉터 예전 의사 은 이렇게 대충 꼬매 놓다 모르다 새롭다 부분 절제 하고 시술 받다 아니다 약 이나 시술 받다 싶다 약 써다 보고 싶다',
  '스킨 오일 크림 노스 카나 울트라 이렇게 총 5 개 바르다 괜찮다 너무 많이 바르다 가요',
  '이름 안녕하다 뺨 울퉁불퉁하다 않다 빨갛다 흔적 자국 여러 개 여드름 날 처럼 하다 안 곪 고 그대로 흉터 남다 피부 가보다 그냥 해결 해주다 지금 고민 중 인 약 노스 카나 겔 콘트락 투 벡스 벤트 락스 겔 스카 힐 더마틱스 울트라 겔 5 개 중 사용 하다 하다 요 추출 물 연고 먼저 바르다 더

### sentiment analysis method 2
### K-Means Clustering 군집화
- clustering 2 or 3 개하면 -> 중심점 -> 유사도  which cluster 

In [ ]:
centers = kmeans.cluster_centers_
print(centers.shape)

centroid_arg_idx = centers.argsort()[:, ::-1]  # tf-idf값이 높은순으로 index 정렬
idx_top_20 = centroid_arg_idx[:, :20]
feature_names = tfidf_vectorizer.get_feature_names_out()
feature_names[idx_top_20]

In [41]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=4,
    max_iter=5000,
    random_state=0
)

opinions_label = kmeans.fit_predict(text_vecs)


# 군집화 핵심 단어 추출
centers = kmeans.cluster_centers_
# print(centers.shape)

centroid_arg_idx = centers.argsort()[:, ::-1]  # tf-idf값이 높은순으로 index 정렬
idx_top_20 = centroid_arg_idx[:, :20]
feature_names = tfidf_vectorizer.get_feature_names_out()
feature_names[idx_top_20]


array([['먹다', '감사하다', '제로', '좋다', '되다', '콜라', '괜찮다', '알콜', '없다', '들다',
        '약사', '들려주다', '이야기', '보다', '그렇다', '비타민', '안좋다', '이다', '나다', '하고'],
       ['하다', '먹다', '되다', '좋다', '들다', '없다', '보다', '복용', '않다', '생각',
        '아니다', '많이', '운동', '비타민', '섭취', '이다', '과당', '그렇다', '이름', '사람'],
       ['과일', '섭취', '때문', '많이', '과당', '먹다', '안좋다', '체워줄', '항산화', '보다는',
        '낫다', '액상과당', '적정', '성분', '괜찮다', '이다', '건가', '좋다', '그렇다', '하다'],
       ['방향', '보시', '겁니다', '줄이다', '조금씩', '드리다', '끊다', '가다', '영상', '그냥',
        '처럼', '보이다', '말씀', '보고', '결론', '이라는', '맞다', '운동', '이다', '금상첨화']],
      dtype=object)